version: '3.7'

services:
  yasgui:
    restart: "no"
  identifier:
    restart: "no"
  dispatcher:
    restart: "no"
  database:
    restart: "no"
  triplestore:
    ports:
      - "8890:8890"
    restart: "no"