version: '3.7'

services:
  frontend:
    image: erikap/yasgui
  identifier:
    image: semtech/mu-identifier:1.9.1
    environment:
      SESSION_COOKIE_SECURE: "on"
      DEFAULT_ACCESS_CONTROL_ALLOW_ORIGIN_HEADER: "*"
    links:
      - dispatcher:dispatcher
  dispatcher:
    image: semtech/mu-dispatcher:2.0.0
    volumes:
      - ./config/dispatcher:/config
  database:
    image: semtech/mu-authorization:0.6.0-beta.7
    environment:
      MU_SPARQL_ENDPOINT: "http://triplestore:8890/sparql"
    volumes:
      - ./config/authorization:/config
  triplestore:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
  migrations:
    image: semtech/mu-migrations-service:0.7.0
    links:
      - triplestore:database
    volumes:
      - ./config/migrations:/data/migrations